// HTTP smoke test: `npm run build && node scripts/smoke-api.mjs [port]`. Starts its own server on a
// throwaway data file (scripts/isolated-server.mjs), walks draft -> approve -> session -> frames -> locale.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { MAX_MEDIA_REQUEST_BYTES } from '../src/shared/mediaLimits.ts';
import { startIsolatedServer } from './isolated-server.mjs';

// The child receives its own media directory, even if the host has an override.
const mediaDir = mkdtempSync(join(tmpdir(), 'breadcrumb-media-smoke-'));
const oldMediaDir = process.env.BREADCRUMB_MEDIA_DIR;
process.env.BREADCRUMB_MEDIA_DIR = mediaDir;
process.on('exit', () => rmSync(mediaDir, { recursive: true, force: true }));
// Explicitly disable extraction for this child; never pass provider credentials.
const savedGeminiEnv = Object.fromEntries(['BREADCRUMB_GEMINI_EXTRACTION', 'GEMINI_API_KEY', 'GEMINI_MODEL'].map((key) => [key, process.env[key]]));
for (const key of Object.keys(savedGeminiEnv)) delete process.env[key];
process.env.BREADCRUMB_GEMINI_EXTRACTION = '0';
const { base } = await startIsolatedServer(Number(process.argv[2] ?? 3107));
for (const [key, value] of Object.entries(savedGeminiEnv)) {
  if (value === undefined) delete process.env[key];
  else process.env[key] = value;
}
if (oldMediaDir === undefined) delete process.env.BREADCRUMB_MEDIA_DIR;
else process.env.BREADCRUMB_MEDIA_DIR = oldMediaDir;
const call = async (method, path, body) => {
  const res = await fetch(base + path, {
    method, headers: body ? { 'content-type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json();
  console.log(method.padEnd(5), path.padEnd(48), res.status, json.ok ? (json.value?.state ?? json.value?.status ?? 'ok') : json.error.code);
  return { status: res.status, ...json };
};

const extractionDisabled = await call('POST', `/api/media/${randomUUID()}/extract`);
assert.equal(extractionDisabled.status, 503);
assert.equal(extractionDisabled.error.code, 'PROVIDER_UNAVAILABLE');
assert.match(extractionDisabled.error.message, /not enabled/);

// Synthetic signature, not playable footage and never used to create a route.
const mp4 = Uint8Array.from([0, 0, 0, 16, 0x66, 0x74, 0x79, 0x70, 0x69, 0x73, 0x6f, 0x6d, 0, 0, 0, 0]);
const upload = async (bytes) => {
  const form = new FormData();
  form.set('file', new File([bytes], 'synthetic.mp4', { type: 'video/mp4' }));
  const res = await fetch(`${base}/api/media`, { method: 'POST', body: form });
  const json = await res.json();
  console.log('POST ', '/api/media'.padEnd(48), res.status, json.ok ? 'stored, extraction pending' : json.error.code);
  return { status: res.status, ...json };
};
const uploaded = await upload(mp4);
assert.equal(uploaded.status, 200);
assert.equal(uploaded.value.extraction, 'pending');
assert.deepEqual(readFileSync(join(mediaDir, `${uploaded.value.mediaId}.mp4`)), Buffer.from(mp4));
assert.deepEqual(JSON.parse(readFileSync(join(mediaDir, `${uploaded.value.mediaId}.json`), 'utf8')), {
  id: uploaded.value.mediaId, originalName: 'synthetic.mp4', type: 'video/mp4', size: mp4.length,
  uploadedAt: uploaded.value.uploadedAt,
});
for (const bytes of [new Uint8Array(), Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8])]) {
  const rejected = await upload(bytes);
  assert.deepEqual([rejected.status, rejected.error.code], [400, 'INVALID_INPUT']);
}
const nonMultipart = await call('POST', '/api/media', { file: 'not a video' });
assert.deepEqual([nonMultipart.status, nonMultipart.error.code], [400, 'INVALID_INPUT']);
assert.equal(readdirSync(mediaDir).length, 2); // rejected uploads and temp files left nothing behind

// A real chunked HTTP upload: no Content-Length and no large fixture on disk.
const beforeOversized = readdirSync(mediaDir).sort();
const boundary = 'breadcrumb-streamed-limit';
const encoder = new TextEncoder();
const prefix = encoder.encode(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="synthetic.mp4"\r\nContent-Type: video/mp4\r\n\r\n`);
const suffix = encoder.encode(`\r\n--${boundary}--\r\n`);
const chunk = new Uint8Array(64 * 1024);
let remaining = MAX_MEDIA_REQUEST_BYTES + chunk.byteLength;
let started = false;
const oversizedRequest = new Request(`${base}/api/media`, {
  method: 'POST', headers: { 'content-type': `multipart/form-data; boundary=${boundary}` },
  duplex: 'half',
  body: new ReadableStream({
    pull(controller) {
      if (!started) {
        started = true;
        controller.enqueue(prefix);
        controller.enqueue(mp4); // signature only; the generated bytes are not playable footage
        remaining -= mp4.byteLength;
      } else if (remaining > 0) {
        const size = Math.min(remaining, chunk.byteLength);
        controller.enqueue(chunk.subarray(0, size));
        remaining -= size;
      } else {
        controller.enqueue(suffix);
        controller.close();
      }
    },
  }),
});
assert.equal(oversizedRequest.headers.get('content-length'), null);
const oversizedResponse = await fetch(oversizedRequest);
const oversizedResult = await oversizedResponse.json();
assert.deepEqual([oversizedResponse.status, oversizedResult.error.code, oversizedResult.error.retryable], [400, 'INVALID_INPUT', false]);
assert.match(oversizedResult.error.message, /upload body is too large/);
assert.deepEqual(readdirSync(mediaDir).sort(), beforeOversized);
console.log('POST ', '/api/media (chunked over cap)'.padEnd(48), oversizedResponse.status, oversizedResult.error.code);

const route = (await call('GET', '/api/routes/demo-route')).value;
assert.equal(route.status, 'draft');
assert.equal((await call('POST', '/api/sessions', { routeId: 'demo-route', locale: 'en', mode: 'mock' })).status, 409);
assert.equal((await call('PUT', '/api/routes/demo-route/draft', { ...route, version: 'x' })).status, 400);
const edited = { ...route, checkpoints: route.checkpoints.map((c) => c.id === 'mural' ? { ...c, instruction: { ...c.instruction, en: 'Turn left at the blue mural.' } } : c) };
assert.equal((await call('PUT', '/api/routes/demo-route/draft', edited)).status, 200);
assert.equal((await call('POST', '/api/routes/demo-route/approve', { version: 1, reviewedCheckpointIds: ['entrance'] })).status, 409);
const ids = route.checkpoints.map((c) => c.id);
assert.equal((await call('POST', '/api/routes/demo-route/approve', { version: 1, reviewedCheckpointIds: ids })).value.status, 'approved');
assert.equal((await call('POST', '/api/sessions', { routeId: 'demo-route', locale: 'en', mode: 'live' })).status, 503);

const s = (await call('POST', '/api/sessions', { routeId: 'demo-route', locale: 'en', mode: 'mock' })).value;
const frame = async (mediaId) => {
  const { sequence, routeVersion } = (await call('POST', `/api/sessions/${s.id}/frame-sequence`, {})).value;
  return call('POST', `/api/sessions/${s.id}/frame`, { sessionId: s.id, routeVersion, sequence, capturedAt: new Date().toISOString(), mediaId });
};
assert.equal((await frame('mock:unrelated')).value.direction, null);
assert.equal((await frame('mock:entrance:unknown-approach')).value.state, 'reorient');
assert.equal((await frame('mock:entrance:approach')).value.direction, 'forward');
assert.equal((await frame('mock:mural:approach')).value.text, 'Turn left at the blue mural.');
assert.equal((await frame('mock:provider-error')).status, 503);
await call('PATCH', `/api/sessions/${s.id}/locale`, { locale: 'es' });
const es = (await call('GET', `/api/sessions/${s.id}/guidance`)).value;
assert.deepEqual([es.state, es.checkpointId, es.direction, es.locale], ['guiding', 'mural', 'left', 'es']);
assert.equal((await frame('mock:destination:approach')).value.text, 'Has llegado a la sala 204.');
assert.equal((await call('POST', `/api/sessions/${s.id}/frame`, { sessionId: s.id, routeVersion: 1, sequence: 1, capturedAt: new Date().toISOString(), mediaId: 'mock:unrelated' })).status, 409);

const actionRouteId = 'action-fixture';
const actionRoute = (await call('GET', `/api/routes/${actionRouteId}`)).value;
const actionCheckpointIds = actionRoute.checkpoints.map((c) => c.id);
assert.equal((await call('POST', `/api/routes/${actionRouteId}/approve`, {
  version: actionRoute.version, reviewedCheckpointIds: actionCheckpointIds,
})).value.status, 'approved');
const actionSession = (await call('POST', '/api/sessions', {
  routeId: actionRouteId, locale: 'en', mode: 'mock',
})).value;
const reserveActionSequence = async () => (await call('POST', `/api/sessions/${actionSession.id}/frame-sequence`, {})).value;
const completeAction = (body) => call('POST', `/api/sessions/${actionSession.id}/complete-action`, body);
const inactiveSequence = await reserveActionSequence();
const inactiveCompletion = await completeAction({
  routeVersion: inactiveSequence.routeVersion, sequence: inactiveSequence.sequence, checkpointId: 'elevator',
});
assert.deepEqual([inactiveCompletion.status, inactiveCompletion.error.code], [400, 'INVALID_INPUT']);

const actionFrame = async (mediaId) => {
  const { sequence, routeVersion } = await reserveActionSequence();
  return call('POST', `/api/sessions/${actionSession.id}/frame`, {
    sessionId: actionSession.id, routeVersion, sequence, capturedAt: new Date().toISOString(), mediaId,
  });
};
const similarDoor = await actionFrame('mock:door-b214:similar-door');
assert.equal(similarDoor.value.checkpointId, null); // B215 evidence must not select B214.
const activeAction = await actionFrame('mock:door-b214:approach');
assert.deepEqual([activeAction.value.state, activeAction.value.checkpointId, activeAction.value.direction], [
  'guiding', 'door-b214', null,
]);

const staleVersionSequence = await reserveActionSequence();
const staleVersion = await completeAction({
  routeVersion: staleVersionSequence.routeVersion + 1,
  sequence: staleVersionSequence.sequence,
  checkpointId: 'door-b214',
});
assert.deepEqual([staleVersion.status, staleVersion.error.code], [409, 'STALE_VERSION']);
const validCompletion = await reserveActionSequence();
const completionRequest = {
  routeVersion: validCompletion.routeVersion,
  sequence: validCompletion.sequence,
  checkpointId: 'door-b214',
};
const completed = await completeAction(completionRequest);
assert.equal(completed.status, 200);
assert.ok(completed.value.evidence.some((e) => e.includes('Manual')));
assert.notEqual(completed.value.state, 'guiding');
assert.equal(completed.value.direction, null);
const repeatedCompletion = await completeAction(completionRequest);
assert.deepEqual([repeatedCompletion.status, repeatedCompletion.error.code], [409, 'STALE_FRAME']);
console.log('smoke passed');
process.exit(0);
